### ISSUE TITLE
Can't alias raw input (missing support for input variants)

### ISSUE THREAD

**Issue by SleeplessByte** [XPBytes/media_types-serialization#104]
Similar to the functionality where we can variant `text/html`, so that user agents still understand what they're doing, it would be great to support this for input too.

A use-case would be to define a raw input `application/vnd.company.thing` which actually expects a `multipart/formdata`. A client can then send `multipart/formdata` with `variant=application/vnd.company.thing` and we can content-neg on it. This makes it possible to support some variants and not all without having to inspect the entire body.

**Comment by thexa4** [comment]
Closed in favor of #107
