### ISSUE TITLE
Improvement for InputValidationFailedError (400 vs 422)

### ISSUE THREAD

**Issue by SleeplessByte** [XPBytes/media_types-serialization#105]
In general, 422 for a failed input validation is a great choice. The server understood the request but something was wrong with it other than the headers, or the format, preconditions, etc.

However, _malformed_ JSON or _empty_ JSON also reports as 422.

```json
{
  "type": "https://docs.delftsolutions.nl/wiki/Error/MediaTypes%3A%3ASerialization%3A%3AInputValidationFailedError",
  "title": "Input failed to validate.",
  "detail": "An empty string is not a valid JSON string.",
  "instance": "https://docs.delftsolutions.nl/wiki/Error/EncodingError"
}
```

For these, 400 Bad Request is probably more appropriate, given some interpretations of the status code.

**Comment by thexa4** [comment]
You're right, we should change the status code for both validation and json errors to 400 instead of 422. 422 assumes the content is already well-formed.
