### ISSUE TITLE
✨ clearer naming

### ISSUE THREAD

**Issue by thexa4** [XPBytes/media_types-serialization#25]
Currently the gem uses `accept_serialization` for data that it can emit. The naming of that function seem to indicate that the controller accepts a certain serialization from the client. Right now there is no support for indicating what kind of content you allow the client to send.

Ideally the interface would look something like:
 - `allow_input_serializer` - allow the client to send content-types that this serializer understands
 - `allow_output_serializer` - allow the controller to emit content-types that this serializer understands
 - `freeze_io!` - lock both

**Comment by SleeplessByte** [comment]
I like this.

Would you like to take it? Or want me to whip it up?

**Comment by thexa4** [comment]
I mainly wanted to write it down before I forgot about it. I might be able to look at it in about a month. If you want it earlier feel free to whip it up :)

**Comment by SleeplessByte** [comment]
Fixed by #31
