### ISSUE TITLE
✨ move view definition to serializer

### ISSUE THREAD

**Issue by thexa4** [XPBytes/media_types-serialization#28]
Currently `accept_serialization` asks you to pass both a serializer and a view. Changing the view parameter changes which functions are called on the serializer and requires you to give it a differently formatted input. Having an object that responds differently based on external state is often confusing.

I'm proposing changing the interface to:
 - `accept_serialization MyResourceSerializer.as_index`
 - `accept_serialization MyResourceSerializer.as_collection`
 - `accept_serialization MyResourceSerializer.as_view(:special)`

**Comment by SleeplessByte** [comment]
I like that.

**Comment by SleeplessByte** [comment]
Fixed by #31
