### ISSUE TITLE
🐛 Should not be able to serialize an unregistered mime type

### ISSUE THREAD

**Issue by thexa4** [XPBytes/media_types-serialization#29]
Causes an Exception to be thrown about an undefined function `to_body`.

In `lib/media_types/serialization/renderer.rb`:

`content_type = options[:content_type]` will sometimes return `Mime::NullType.instance.to_s`. The same happens with `self.content_type&.to_s` in that case.

Adding a check for `content_type == Mime::NullType.instance.to_s` at the end and falling back to `obj.current_media_type.to_s` succesfully hides the issue.

**Comment by thexa4** [comment]
Workaround doesn't fully hide the issue.

**Comment by SleeplessByte** [comment]
Sounds like format being null which is the case if a client passes in
_only_ */* I think?

**Comment by SleeplessByte** [comment]
Fixed by #31
