### ISSUE TITLE
Improve hint for ouput alias error

### ISSUE THREAD

**Issue by VincentRbbmnd** [XPBytes/media_types-serialization#57]
When creating an `output_alias` for a defined (and versioned) output in a `Serializer`, an error will be thrown if there exists no definition of the output without a version, for example:

```ruby
# frozen_string_literal: true

require 'media_types/serialization/base'

class Serializer < ::MediaTypes::Serialization::Base
  unvalidated 'application/vnd.coffee.beans'

  output version: 1 do |beans, _version, _context|
    attribute :beans do
      attribute :name, beans[:name]
      attribute :origin, beans[:origin]
    end
  end

  output_alias 'application/json'

end
```

This will result in the following error:
```shell
MediaTypes::Serialization::UnbackedAliasDefinitionError: Serializer tried to define an output_alias that points to the media type identifier application/vnd.coffee.beans but no such output has been defined yet. Please move the output definition above the alias.

Move the output definition above the alias:

class MySerializer < MediaTypes::Serialization::Base
#...
output do
  # ...
end

output_alias 'text/html'
# ^----- move here
end
```

In this situation the error message might seem confusing as the `output_alias` is defined exactly where the error message is telling you to.

Since this error is remedied by defining an output without a version, a useful hint might be to show what outputs are currently actually defined. Which in this case would be `application/vnd.coffee.beans.v1` and would hint the absence of `application/vnd/coffee.beans`

**Comment by SleeplessByte** [comment]
If we can detect this, that would be super nice.

Similar: when input do is missing in a contract, but it's used in allow_input_ we tell the developer that it's probably because of incorrect views. If we can detect which views exist and which don't, that would be super helpful.

Might be the same code path we need to add,which is why I'm mentioning it.

**Comment by thexa4** [comment]
This issue is fixed and should be closed
