### ISSUE TITLE
Impossible to alias raw input with version if unvalidated

### ISSUE THREAD

**Issue by SleeplessByte** [XPBytes/media_types-serialization#83]
```ruby
class Contract < ApplicationContract
  unvalidated 'application/vnd.bnbbutler.booking'
  input_raw(view: :'check-in', version: 1)
  input_alias 'multipart/form-data', view: :'check-in'
end
```

```ruby
# Serializer tried to define an input_alias that points to the media type identifier 
# application/vnd.bnbbutler.booking.check-in but no such input has been defined yet. 
# Please move the input definition above the alias.

# Move the output definition above the alias:
class MySerializer < MediaTypes::Serialization::Base
#...
output do
  # ...
end
output_alias 'text/html'
# ^----- move here
end
```

It doesn't recognise the version in this case and produces an incorrect alias. `version` can not be given to `input_alias`.

## Expected result

Either an error message that matches my code, or it is possible

## Actual result

Message contains `output_alias` instead of `input_alias`, and it's unclear that this is by design because `version` is ignored.

**Comment by thexa4** [comment]
Is by design but error message should be clearer if already defined with version above.

**Comment by thexa4** [comment]
Related to input aliases issue: https://github.com/XPBytes/media_types-serialization/issues/57
