### ISSUE TITLE
Packaging is harder due to having very small dependencies

### ISSUE THREAD

**Issue by thexa4** [XPBytes/media_types-serialization#93]
We should probably investigate if we can inline some of the header dependencies.

**Comment by SleeplessByte** [comment]
```ruby
  spec.add_dependency 'actionpack', '>= 4.0.0'
  spec.add_dependency 'activesupport', '>= 4.0.0'
  spec.add_dependency 'media_types', '>= 2.0.0', '< 3.0.0'
  spec.add_dependency 'http_headers-accept', '>= 0.2.2', '< 1.0.0'
  spec.add_dependency 'http_headers-link', '< 1.0.0'
```

The last two we can pull in as a "build script" / "sync script" and vendor? The first three we've already packaged/already exist as package, right?

**Comment by thexa4** [comment]
It's mainly the http header libs yes. I don't think we can do a sync script without making the packaging even harder, gem2deb expects the apt packages to be equal to the gems.

My suggestion would be to merge these gems into this one:
 - http_header-utils
 - http_headers-accept
 - http_headers-accept-language
 - http_headers-link
 - http_headers-content-type

They don't have any reverse dependencies other than media_types-serialization. Do you know if those gems are used anywhere media_types-serialization isn't used?
